import { Component, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { HttpErrorMockingControl } from '@cockpit/app/core/errorHandling/errorMocking/httpErrorMockingControl.component';
import { environment } from '@cockpit/environments';
import { GridstackComponent } from 'gridstack/dist/angular';
import { PegelWidget } from './feature/dashboard/widgets/pegel-widget/pegel-widget';
import { WeatherAlertWidget } from './feature/dashboard/widgets/weather-alert-widget/weather-alert-widget';
import { WeatherWidget } from './feature/dashboard/widgets/weather-widget/weather-widget';

/* ---- AI disclaimer ----

The rather low rate of spelling errors, clean formatting and consistent code structure is due to the fact that I'm using a spell checker, code formatter and linter. (see extension in .vscode/settings.json)

This might lead to the false impression that the code or the comments are completely ai generated.
Sections that were generated by contain a disclaimer, all else is written by me, using the autocomplete feature of the ai co-pilot

Furthermore some(!) lookups, that used to be a google search were outsourced to the ai with a ask-prompt,
to avoid having to scan 5 stack overflow pages or using the search feature on an api documentation.

AI in aks mode was also used to rubber-duck the infinite loop error logging issue
and finding the most elegant solution for passing the context to the content of the async-data-outlet.

---- AI disclaimer ---- */

@Component({
	selector: 'app-root',
	imports: [HttpErrorMockingControl, RouterOutlet],
	template: `
		<router-outlet />
		@if (!environment.production) {
			<app-http-error-period-control />
		}
	`,
	styles: `
		:host {
			box-sizing: border-box;
			padding: 1rem;
			display: block;
			height: 100%;
			background-color: var(--mat-sys-surface-variant);
		}
	`,
})
export class App {
	protected readonly environment = environment;
	protected readonly title = signal('Hafen-Cockpit');
	constructor() {
		GridstackComponent.addComponentToSelectorType([PegelWidget, WeatherWidget, WeatherAlertWidget]);
	}
}
